#############################################################################
# Makefile for building: papaya
# Generated by qmake (2.01a) (Qt 4.5.3) on: Wed Jan 20 21:09:05 2010
# Project:  papaya.pro
# Template: app
# Command: /usr/lib/qt4.5.3/bin/qmake -spec /usr/lib/qt4.5.3/mkspecs/linux-g++ -unix -o Makefile papaya.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -g $(DEFINES)
CXXFLAGS      = -pipe -g $(DEFINES)
INCPATH       = -I/usr/lib/qt4.5.3/mkspecs/linux-g++ -I. -I/usr/include
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/lib/qt4.5.3/lib
LIBS          = $(SUBLIBS)   -lboost_program_options-mt
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/qt4.5.3/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		utils/text_utils.cpp \
		utils/settings.cpp \
		utils/node.cpp \
		utils/newick_reader.cpp \
		utils/model_factory.cpp \
		utils/fasta_reader.cpp \
		utils/eigen.cpp \
		utils/db_matrix.cpp \
		main/sequence.cpp \
		main/simple_alignment.cpp \
		utils/int_matrix.cpp \
		utils/settings_handle.cpp \
		utils/xml_writer.cpp \
		utils/evol_model.cpp \
		main/reads_alignment.cpp 
OBJECTS       = main.o \
		text_utils.o \
		settings.o \
		node.o \
		newick_reader.o \
		model_factory.o \
		fasta_reader.o \
		eigen.o \
		db_matrix.o \
		sequence.o \
		simple_alignment.o \
		int_matrix.o \
		settings_handle.o \
		xml_writer.o \
		evol_model.o \
		reads_alignment.o
DIST          = /usr/lib/qt4.5.3/mkspecs/common/g++.conf \
		/usr/lib/qt4.5.3/mkspecs/common/unix.conf \
		/usr/lib/qt4.5.3/mkspecs/common/linux.conf \
		/usr/lib/qt4.5.3/mkspecs/qconfig.pri \
		/usr/lib/qt4.5.3/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4.5.3/mkspecs/features/qt_config.prf \
		/usr/lib/qt4.5.3/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4.5.3/mkspecs/features/default_pre.prf \
		/usr/lib/qt4.5.3/mkspecs/features/debug.prf \
		/usr/lib/qt4.5.3/mkspecs/features/default_post.prf \
		papaya.pro
QMAKE_TARGET  = papaya
DESTDIR       = 
TARGET        = papaya

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: papaya.pro  /usr/lib/qt4.5.3/mkspecs/linux-g++/qmake.conf /usr/lib/qt4.5.3/mkspecs/common/g++.conf \
		/usr/lib/qt4.5.3/mkspecs/common/unix.conf \
		/usr/lib/qt4.5.3/mkspecs/common/linux.conf \
		/usr/lib/qt4.5.3/mkspecs/qconfig.pri \
		/usr/lib/qt4.5.3/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4.5.3/mkspecs/features/qt_config.prf \
		/usr/lib/qt4.5.3/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4.5.3/mkspecs/features/default_pre.prf \
		/usr/lib/qt4.5.3/mkspecs/features/debug.prf \
		/usr/lib/qt4.5.3/mkspecs/features/default_post.prf
	$(QMAKE) -spec /usr/lib/qt4.5.3/mkspecs/linux-g++ -unix -o Makefile papaya.pro
/usr/lib/qt4.5.3/mkspecs/common/g++.conf:
/usr/lib/qt4.5.3/mkspecs/common/unix.conf:
/usr/lib/qt4.5.3/mkspecs/common/linux.conf:
/usr/lib/qt4.5.3/mkspecs/qconfig.pri:
/usr/lib/qt4.5.3/mkspecs/features/qt_functions.prf:
/usr/lib/qt4.5.3/mkspecs/features/qt_config.prf:
/usr/lib/qt4.5.3/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt4.5.3/mkspecs/features/default_pre.prf:
/usr/lib/qt4.5.3/mkspecs/features/debug.prf:
/usr/lib/qt4.5.3/mkspecs/features/default_post.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/lib/qt4.5.3/mkspecs/linux-g++ -unix -o Makefile papaya.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/papaya1.0.0 || $(MKDIR) .tmp/papaya1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/papaya1.0.0/ && (cd `dirname .tmp/papaya1.0.0` && $(TAR) papaya1.0.0.tar papaya1.0.0 && $(COMPRESS) papaya1.0.0.tar) && $(MOVE) `dirname .tmp/papaya1.0.0`/papaya1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/papaya1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


compiler_clean: 

####### Compile

main.o: main.cpp utils/settings.h \
		utils/settings_handle.h \
		utils/newick_reader.h \
		utils/exceptions.h \
		utils/node.h \
		main/sequence.h \
		main/simple_alignment.h \
		utils/evol_model.h \
		utils/db_matrix.h \
		utils/int_matrix.h \
		utils/model_factory.h \
		utils/fasta_entry.h \
		utils/fasta_reader.h \
		utils/xml_writer.h \
		main/reads_alignment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

text_utils.o: utils/text_utils.cpp utils/text_utils.h \
		utils/exceptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o text_utils.o utils/text_utils.cpp

settings.o: utils/settings.cpp utils/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o utils/settings.cpp

node.o: utils/node.cpp utils/node.h \
		utils/exceptions.h \
		utils/settings.h \
		utils/settings_handle.h \
		main/sequence.h \
		main/simple_alignment.h \
		utils/evol_model.h \
		utils/db_matrix.h \
		utils/int_matrix.h \
		utils/model_factory.h \
		utils/fasta_entry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o utils/node.cpp

newick_reader.o: utils/newick_reader.cpp utils/newick_reader.h \
		utils/exceptions.h \
		utils/node.h \
		utils/settings.h \
		utils/settings_handle.h \
		main/sequence.h \
		main/simple_alignment.h \
		utils/evol_model.h \
		utils/db_matrix.h \
		utils/int_matrix.h \
		utils/model_factory.h \
		utils/fasta_entry.h \
		utils/text_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newick_reader.o utils/newick_reader.cpp

model_factory.o: utils/model_factory.cpp utils/model_factory.h \
		utils/db_matrix.h \
		utils/int_matrix.h \
		utils/evol_model.h \
		utils/settings.h \
		utils/settings_handle.h \
		utils/eigen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model_factory.o utils/model_factory.cpp

fasta_reader.o: utils/fasta_reader.cpp utils/fasta_reader.h \
		utils/exceptions.h \
		utils/node.h \
		utils/settings.h \
		utils/settings_handle.h \
		main/sequence.h \
		main/simple_alignment.h \
		utils/evol_model.h \
		utils/db_matrix.h \
		utils/int_matrix.h \
		utils/model_factory.h \
		utils/fasta_entry.h \
		utils/text_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fasta_reader.o utils/fasta_reader.cpp

eigen.o: utils/eigen.cpp utils/eigen.h \
		utils/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eigen.o utils/eigen.cpp

db_matrix.o: utils/db_matrix.cpp utils/db_matrix.h \
		utils/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o db_matrix.o utils/db_matrix.cpp

sequence.o: main/sequence.cpp utils/settings.h \
		main/sequence.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sequence.o main/sequence.cpp

simple_alignment.o: main/simple_alignment.cpp main/simple_alignment.h \
		utils/evol_model.h \
		utils/db_matrix.h \
		utils/int_matrix.h \
		utils/settings.h \
		utils/settings_handle.h \
		main/sequence.h \
		utils/exceptions.h \
		utils/node.h \
		utils/model_factory.h \
		utils/fasta_entry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simple_alignment.o main/simple_alignment.cpp

int_matrix.o: utils/int_matrix.cpp utils/int_matrix.h \
		utils/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o int_matrix.o utils/int_matrix.cpp

settings_handle.o: utils/settings_handle.cpp utils/settings_handle.h \
		utils/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings_handle.o utils/settings_handle.cpp

xml_writer.o: utils/xml_writer.cpp utils/xml_writer.h \
		utils/exceptions.h \
		utils/node.h \
		utils/settings.h \
		utils/settings_handle.h \
		main/sequence.h \
		main/simple_alignment.h \
		utils/evol_model.h \
		utils/db_matrix.h \
		utils/int_matrix.h \
		utils/model_factory.h \
		utils/fasta_entry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xml_writer.o utils/xml_writer.cpp

evol_model.o: utils/evol_model.cpp utils/evol_model.h \
		utils/db_matrix.h \
		utils/int_matrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o evol_model.o utils/evol_model.cpp

reads_alignment.o: main/reads_alignment.cpp main/reads_alignment.h \
		utils/settings.h \
		utils/settings_handle.h \
		utils/model_factory.h \
		utils/db_matrix.h \
		utils/int_matrix.h \
		utils/evol_model.h \
		utils/fasta_entry.h \
		utils/fasta_reader.h \
		utils/exceptions.h \
		utils/node.h \
		main/sequence.h \
		main/simple_alignment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reads_alignment.o main/reads_alignment.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

