#############################################################################
# Makefile for building: pagan
#############################################################################

####### Compiler, tools and options

CC       = /usr/bin/gcc
CXX      = /usr/bin/g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -Wno-unused -O2 
CXXFLAGS = -pipe -Wall -W -Wno-unused -O2 
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/include -I. -I./utils -I./main -I../boost/include
LINK     = /usr/bin/g++
LFLAGS   = 
LIBS     = $(SUBLIBS)  -Wl,-rpath, -lboost_program_options -lboost_regex -lboost_thread -lm -lrt -L../boost/lib
AR       = ar cqs
RANLIB   = 
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY) -p
COPY_DIR = $(COPY) -pR
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS       = utils/text_utils.h \
		utils/settings.h \
		utils/newick_reader.h \
		utils/model_factory.h \
		utils/fasta_reader.h \
		utils/eigen.h \
		utils/exceptions.h \
		utils/db_matrix.h \
		utils/int_matrix.h \
		utils/fasta_entry.h \
		utils/settings_handle.h \
		utils/xml_writer.h \
		utils/evol_model.h \
                utils/check_version.h \
		utils/optimal_reference.h \
		utils/log_output.h \
                main/node.h \
		main/sequence.h \
		main/basic_alignment.h \
		main/viterbi_alignment.h \
		main/reference_alignment.h \
		main/reads_aligner.h
SOURCES       = main.cpp \
		utils/text_utils.cpp \
		utils/settings.cpp \
		utils/newick_reader.cpp \
		utils/model_factory.cpp \
		utils/fasta_reader.cpp \
		utils/eigen.cpp \
		utils/db_matrix.cpp \
		utils/int_matrix.cpp \
		utils/settings_handle.cpp \
		utils/xml_writer.cpp \
		utils/evol_model.cpp \
		utils/check_version.cpp \
		utils/exonerate_reads.cpp \
		utils/optimal_reference.cpp \
		utils/log_output.cpp \
		main/node.cpp \
		main/sequence.cpp \
		main/basic_alignment.cpp \
		main/viterbi_alignment.cpp \
		main/reference_alignment.cpp \
		main/reads_aligner.cpp
OBJECTS       = main.o \
		text_utils.o \
		settings.o \
		newick_reader.o \
		model_factory.o \
		fasta_reader.o \
		eigen.o \
		db_matrix.o \
		sequence.o \
		int_matrix.o \
		settings_handle.o \
		xml_writer.o \
		evol_model.o \
		check_version.o \
		exonerate_reads.o \
		optimal_reference.o \
		log_output.o \
		node.o \
		reference_alignment.o \
		viterbi_alignment.o \
		basic_alignment.o \
		reads_aligner.o
TARGET   = pagan

first: all
####### Implicit rules

.SUFFIXES: .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET): $(OBJECTS)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS)

clean:
	-$(DEL_FILE) $(OBJECTS) 
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

main.o: main.cpp utils/settings.h \
		utils/settings_handle.h \
		utils/newick_reader.h \
		utils/exceptions.h \
		main/node.h \
		main/sequence.h \
		utils/fasta_entry.h \
		main/viterbi_alignment.h \
		utils/evol_model.h \
		utils/db_matrix.h \
		utils/log_output.h \
		utils/int_matrix.h \
		main/basic_alignment.h \
		utils/model_factory.h \
		main/reference_alignment.h \
		utils/fasta_reader.h \
		utils/xml_writer.h \
		utils/optimal_reference.h \
		main/reads_aligner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

text_utils.o: utils/text_utils.cpp utils/text_utils.h \
		utils/exceptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o text_utils.o utils/text_utils.cpp

settings.o: utils/settings.cpp utils/settings.h \
		utils/check_version.h \
		utils/log_output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o utils/settings.cpp

newick_reader.o: utils/newick_reader.cpp utils/newick_reader.h \
		utils/exceptions.h \
		main/node.h \
		utils/settings.h \
		utils/settings_handle.h \
		main/sequence.h \
		utils/fasta_entry.h \
		main/viterbi_alignment.h \
		utils/evol_model.h \
		utils/db_matrix.h \
		utils/log_output.h \
		utils/int_matrix.h \
		main/basic_alignment.h \
		utils/model_factory.h \
		main/reference_alignment.h \
		utils/text_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newick_reader.o utils/newick_reader.cpp

model_factory.o: utils/model_factory.cpp utils/model_factory.h \
		utils/db_matrix.h \
		utils/log_output.h \
		utils/int_matrix.h \
		utils/evol_model.h \
		utils/settings.h \
		utils/settings_handle.h \
		utils/eigen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model_factory.o utils/model_factory.cpp

fasta_reader.o: utils/fasta_reader.cpp utils/fasta_reader.h \
		utils/exceptions.h \
		main/node.h \
		utils/settings.h \
		utils/settings_handle.h \
		main/sequence.h \
		utils/fasta_entry.h \
		main/viterbi_alignment.h \
		utils/evol_model.h \
		utils/db_matrix.h \
		utils/log_output.h \
		utils/int_matrix.h \
		main/basic_alignment.h \
		utils/model_factory.h \
		main/reference_alignment.h \
		utils/text_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fasta_reader.o utils/fasta_reader.cpp

eigen.o: utils/eigen.cpp utils/eigen.h \
		utils/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eigen.o utils/eigen.cpp

db_matrix.o: utils/db_matrix.cpp utils/db_matrix.h \
		utils/log_output.h \
		utils/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o db_matrix.o utils/db_matrix.cpp

sequence.o: main/sequence.cpp utils/settings.h \
		utils/model_factory.h \
		utils/db_matrix.h \
		utils/log_output.h \
		utils/int_matrix.h \
		utils/evol_model.h \
		utils/settings_handle.h \
		main/sequence.h \
		utils/fasta_entry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sequence.o main/sequence.cpp

int_matrix.o: utils/int_matrix.cpp utils/int_matrix.h \
		utils/log_output.h \
		utils/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o int_matrix.o utils/int_matrix.cpp

settings_handle.o: utils/settings_handle.cpp utils/settings_handle.h \
		utils/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings_handle.o utils/settings_handle.cpp

xml_writer.o: utils/xml_writer.cpp utils/xml_writer.h \
		utils/exceptions.h \
		main/node.h \
		utils/settings.h \
		utils/settings_handle.h \
		main/sequence.h \
		utils/fasta_entry.h \
		main/viterbi_alignment.h \
		utils/evol_model.h \
		utils/db_matrix.h \
		utils/log_output.h \
		utils/int_matrix.h \
		main/basic_alignment.h \
		utils/model_factory.h \
		main/reference_alignment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xml_writer.o utils/xml_writer.cpp

evol_model.o: utils/evol_model.cpp utils/evol_model.h \
		utils/db_matrix.h \
		utils/log_output.h \
		utils/int_matrix.h \
		utils/model_factory.h \
		utils/settings.h \
		utils/settings_handle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o evol_model.o utils/evol_model.cpp

node.o: main/node.cpp main/node.h \
		utils/exceptions.h \
		utils/settings.h \
		utils/settings_handle.h \
		main/sequence.h \
		utils/fasta_entry.h \
		main/viterbi_alignment.h \
		utils/evol_model.h \
		utils/db_matrix.h \
		utils/log_output.h \
		utils/int_matrix.h \
		main/basic_alignment.h \
		utils/model_factory.h \
		main/reference_alignment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o main/node.cpp

reference_alignment.o: main/reference_alignment.cpp main/reference_alignment.h \
		utils/evol_model.h \
		utils/db_matrix.h \
		utils/log_output.h \
		utils/int_matrix.h \
		utils/settings.h \
		utils/settings_handle.h \
		main/sequence.h \
		utils/fasta_entry.h \
		main/basic_alignment.h \
		utils/model_factory.h \
		utils/exceptions.h \
		main/node.h \
		main/viterbi_alignment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reference_alignment.o main/reference_alignment.cpp

viterbi_alignment.o: main/viterbi_alignment.cpp main/viterbi_alignment.h \
		utils/evol_model.h \
		utils/db_matrix.h \
		utils/log_output.h \
		utils/int_matrix.h \
		utils/settings.h \
		utils/settings_handle.h \
		main/sequence.h \
		utils/fasta_entry.h \
		main/basic_alignment.h \
		utils/model_factory.h \
		utils/exceptions.h \
		main/node.h \
		main/reference_alignment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viterbi_alignment.o main/viterbi_alignment.cpp

basic_alignment.o: main/basic_alignment.cpp main/basic_alignment.h \
		utils/model_factory.h \
		utils/db_matrix.h \
		utils/log_output.h \
		utils/int_matrix.h \
		utils/evol_model.h \
		utils/settings.h \
		utils/settings_handle.h \
		main/sequence.h \
		utils/fasta_entry.h \
		utils/exceptions.h \
		main/node.h \
		main/viterbi_alignment.h \
		main/reference_alignment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o basic_alignment.o main/basic_alignment.cpp

reads_aligner.o: main/reads_aligner.cpp main/reads_aligner.h \
		utils/settings.h \
		utils/settings_handle.h \
		utils/model_factory.h \
		utils/db_matrix.h \
		utils/log_output.h \
		utils/int_matrix.h \
		utils/evol_model.h \
		utils/fasta_entry.h \
		utils/fasta_reader.h \
		utils/exceptions.h \
		main/node.h \
		main/sequence.h \
		main/viterbi_alignment.h \
		main/basic_alignment.h \
		main/reference_alignment.h \
		utils/exonerate_reads.h \
		utils/text_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reads_aligner.o main/reads_aligner.cpp

check_version.o: utils/check_version.cpp utils/check_version.h \
		utils/log_output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o check_version.o utils/check_version.cpp

exonerate_reads.o: utils/exonerate_reads.cpp utils/exonerate_reads.h \
		utils/fasta_entry.h \
		main/node.h \
		utils/exceptions.h \
		utils/settings.h \
		utils/settings_handle.h \
		main/sequence.h \
		main/viterbi_alignment.h \
		utils/evol_model.h \
		utils/db_matrix.h \
		utils/log_output.h \
		utils/int_matrix.h \
		main/basic_alignment.h \
		utils/model_factory.h \
		main/reference_alignment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exonerate_reads.o utils/exonerate_reads.cpp

optimal_reference.o: utils/optimal_reference.cpp utils/optimal_reference.h \
		utils/fasta_entry.h \
		main/node.h \
		utils/exceptions.h \
		utils/settings.h \
		utils/settings_handle.h \
		main/sequence.h \
		main/viterbi_alignment.h \
		utils/evol_model.h \
		utils/db_matrix.h \
		utils/log_output.h \
		utils/int_matrix.h \
		main/basic_alignment.h \
		utils/model_factory.h \
		main/reference_alignment.h \
		utils/fasta_reader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optimal_reference.o utils/optimal_reference.cpp

log_output.o: utils/log_output.cpp utils/log_output.h \
		utils/settings_handle.h \
		utils/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o log_output.o utils/log_output.cpp

####### Install

install: all 

uninstall: 

